# Generated by Django 3.2.5 on 2021-08-26 07:23

import assignments.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_auto_20210803_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.JSONField(default=assignments.models.assignment_default, max_length=5000)),
                ('title', models.CharField(default='title', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='questioncomponent',
            name='question',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='title',
        ),
        migrations.AddField(
            model_name='assignment',
            name='schema',
            field=models.JSONField(default=assignments.models.assignment_default, max_length=5000),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionComponent',
        ),
        migrations.AddField(
            model_name='assignment',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assignments.assignmenttemplate'),
        ),
    ]
